Small refactoring/Preparation for summaries
tomwendel/octoawesome pull request #300
Opened 2021-12-12 16:53 UTC by jvbsl

* Introduced nullability
* Fixed some nullability problems
* Refactored old C# style to more recent ones
* Removed unused usings
* Removed some unused code
* Fixed some spelling mistakes
* Updated engenious to newer version(for better nullability compatibility)

2021-12-12 23:02 UTC, Gallimathias requested changes
Part 1

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Basics/Biomes/BiomeBase.cs
> +        public virtual void GetHeightmap(Index2 chunkIndex, float[] heightmap)
FillHeightmap

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Basics/Biomes/IBiome.cs
> +        void GetHeightmap(Index2 chunkIndex, float[] heightmap);
Name wie besprochen

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Basics/Biomes/LargeBiomeBase.cs
> +        protected IBiome? ChooseBiome(float value, out IBiome? secondBiome)
```suggestion

        protected IBiome? ChooseBiome(float value, out IBiome? secondBiome)
```

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Basics/Biomes/LargeBiomeBase.cs
> +        protected float CalculateInterpolationValue(float region, out IBiome? biome1, out IBiome? biome2)
```suggestion

        protected float CalculateInterpolationValue(float region, out IBiome? biome1, out IBiome? biome2)
```

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Basics/Biomes/LargeBiomeBase.cs
> +        protected float CalculateInterpolationValue(float region, IBiome? biome1, IBiome? biome2)
```suggestion

        protected float CalculateInterpolationValue(float region, IBiome? biome1, IBiome? biome2)
```

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Basics/Biomes/OceanBiomeGenerator.cs
> +        public override void GetHeightmap(Index2 chunkIndex, float[] heightmap)
```suggestion

        public override void GetHeightmap(Index2 chunkIndex, float[] heightmap)
```

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Basics/Biomes/SurfaceBiomeGenerator.cs
> +        public override void GetHeightmap(Index2 chunkIndex, float[] heightmap)
```suggestion

        public override void GetHeightmap(Index2 chunkIndex, float[] heightmap)
```

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Basics/ComplexPlanet.cs
> +        public ComplexPlanet()
```suggestion

        public ComplexPlanet()
```

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Basics/Definitions/Blocks/BirchWoodBlockDefinition.cs
> +                                                      "birch_wood_side" };
die formatierung sieht irgendwie merkwürdig aus

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Basics/Definitions/Blocks/GrassBlockDefinition.cs
> +        public override string[] Textures { get; } = { "grass_top",
Formatierung

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Basics/Definitions/Blocks/GrassBlockDefinition.cs
> +            return wall switch
hier geht auch `=>`

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Basics/Definitions/Blocks/SnowBlockDefinition.cs
> +            return wall switch
hier geht auch `=>`

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Basics/Definitions/Items/AxeDefinition.cs
> +            return material is ISolidMaterialDefinition;
Hier geht auch `=>`

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Basics/Definitions/Items/BucketDefinition.cs
> +            return material is IFluidMaterialDefinition;
hier geht auch `=>`

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Basics/Definitions/Items/PickAxeDefinition.cs
> +            return material is ISolidMaterialDefinition;
Hier geht auch `=>`

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Basics/Definitions/Items/ShovelDefinition.cs
> +            return material is ISolidMaterialDefinition;
`=>`

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Basics/EntityComponents/BodyPowerComponent.cs
> +        public int JumpTime { get; set; }
```suggestion
        public int JumpTime { get; set; }
        
```

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Basics/Entities/WauziEntity.cs
> +        public int JumpTime { get; set; }
```suggestion
        public int JumpTime { get; set; }
        
```

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Basics/Noise/INoise.cs
> +        void GetTileableNoiseMap2D(int startX, int startY, int width, int height, int tileSizeX, int tileSizeY,
evtl, auch Fill?

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Basics/SimulationComponents/BlockInteractionComponent.cs
> +                if (blockHitInformation.Valid && blockHitInformation.List != null)
```suggestion
                if (blockHitInformation.Valid && blockHitInformation.List is not null)
```

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Client.UI/Controls/GroupBox.cs
> +            StackPanel headlinePanel = new(manager)
Entweder das eine oder das andere. Zmd. in der selben methode

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Client/Cache/ChunkRendererDbContext.cs
> +                throw new ArgumentNullException(nameof(value));
```suggestion
                throw new ArgumentNullException(nameof(value));
                
```

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Client/Cache/ChunkRendererDbContext.cs
> +            verticesForChunk.Deserialize(reader);
```suggestion

            verticesForChunk.Deserialize(reader);
```

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Client/Cache/ChunkRendererDbContext.cs
> +                throw new ArgumentNullException(nameof(value));
```suggestion
                throw new ArgumentNullException(nameof(value));
                
```

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Client/Control/DebugControl.cs
> +            if (Player.CurrentEntity == null || Player.CurrentEntityHead == null)
Was ist mit dem Player selbst?

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Client/Control/ExtensionsOptionControl.cs
> +                    throw new NullReferenceException("Enable button should not be clickable when no item is selected.");
```suggestion
                    throw new NullReferenceException("Enable button should not be clickable when no item is selected.");
                    
```

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Client/Control/ExtensionsOptionControl.cs
> +                    throw new NullReferenceException("Disable button should not be clickable when no item is selected.");
```suggestion
                    throw new NullReferenceException("Disable button should not be clickable when no item is selected.");
                    
```

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Client/Control/ResourcePacksOptionControl.cs
> +                    throw new NullReferenceException("Add button should not be clickable when no item is selected.");
```suggestion
                    throw new NullReferenceException("Add button should not be clickable when no item is selected.");
                    
```

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Client/Control/ResourcePacksOptionControl.cs
> +                    throw new NullReferenceException("Remove button should not be clickable when no item is selected.");
```suggestion
                    throw new NullReferenceException("Remove button should not be clickable when no item is selected.");
                    
```

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Client/Crew/CrewMember.cs
> +                    }
```suggestion
                    if (res is List<CrewMember> crewMembers)
                    {
                        return crewMembers;
                    }
```

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Client/Program.cs
> +                        logger.Fatal(message);
```suggestion
                        logger.Fatal(message);
                        
```

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Database/GuidTag.cs
> +        public override bool Equals(object? obj)
```suggestion

        public override bool Equals(object? obj)
```

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Database/ITag.cs
> +        void FromBytes(byte[] array, int startIndex); // TODO: use span
Mach doch aus den ToDos ein Issue. Im Code bleibt das 10000 Jahre

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Database/IdTag.cs
> +        public override bool Equals(object? obj)
```suggestion
            => Id = BitConverter.ToInt32(array, startIndex);
            
        public override bool Equals(object? obj)
```

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.GameServer/Commands/GeneralCommands.cs
> +        public static byte[] GetUniverse(CommandParameter parameter) // TODO: use parameter for multi universe server?
Hier das Selbe, lieber issue statt code ToDo

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Network/ServerNotifications/ServerDataNotification.cs
> +        public override bool Match<T>(T filter)
```suggestion

        public override bool Match<T>(T filter)
```

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Network/Settings.cs
> +                throw new ArgumentException("No file info was specified");
```suggestion
                throw new ArgumentException("No file info was specified");
                
```

2021-12-12 23:02 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Network/Settings.cs
> +                throw new ArgumentException("No file info was specified");
```suggestion
                throw new ArgumentException("No file info was specified");
                
```

2021-12-18 11:49 UTC, Gallimathias requested changes

2021-12-18 11:49 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Runtime/ResourceManager.cs
> +                var retValues = persistenceManager.GetAllComponents<T>(CurrentUniverse.Id).ToArray(); //TODO: HACK will be changed
```suggestion
                var retValues = persistenceManager.GetAllComponents<T>(CurrentUniverse.Id).ToArray(); //HACK: will be changed
```

2021-12-18 17:19 UTC, jvbsl commented on OctoAwesome/OctoAwesome.Client/Crew/CrewMember.cs
> +                    }
obwohl der XmlSerializer mit `typeof(List<CrewMember>)` initialisiert wurde?

2021-12-18 17:23 UTC, jvbsl commented on OctoAwesome/OctoAwesome.Runtime/ResourceManager.cs
> +                var retValues = persistenceManager.GetAllComponents<T>(CurrentUniverse.Id).ToArray(); //TODO: HACK will be changed
Bei Rider wird HACK: nicht als special comment hervorgehoben. Passiert das etwa bei VS? Oder was spricht gegen das TODO?

2022-04-04 20:10 UTC, Gallimathias requested changes

2022-04-04 20:10 UTC, Gallimathias commented on OctoAwesome/OctoAwesome.Basics/Biomes/OceanBiomeGenerator.cs
> +            : base(planet, minValue, maxValue, valueRangeOffset, valueRange, null!) // TODO: currently no noise value is used for the biome floor
Gibts zu dem Todo ein issue?

2022-04-04 21:04 UTC, Gallimathias approved these changes

2022-04-04 21:09 UTC, merged