Playgroundsusch
tomwendel/octoawesome pull request #322
Opened 2022-10-18 18:42 UTC by susch19

* added enumeration modifiable list to reduce the amount of locks required
* added wauzi spawn egg function
* added interaction with wauzi
* made preview of item textures always the same file

2022-10-25 10:25 UTC, jvbsl requested changes

2022-10-25 10:25 UTC, jvbsl commented on OctoAwesome/OctoAwesome.Basics/FunctionBlocks/Chest.cs
> +
```suggestion
```

2022-10-25 10:25 UTC, jvbsl commented on OctoAwesome/OctoAwesome.Client/Components/IViewCreator.cs
> +    public bool IsFirstPerson { get; }
```suggestion
    bool IsFirstPerson { get; }
```

2022-10-25 10:25 UTC, jvbsl commented on OctoAwesome/OctoAwesome.Client/Components/IViewCreator.cs
> +    public (Vector3 cameraPosition, Vector3 lookAt, Vector3 cameraUpVector) CreateCameraUpVectorAndView(HeadComponent head, Coordinate playerPos);
```suggestion
    (Vector3 cameraPosition, Vector3 lookAt, Vector3 cameraUpVector) CreateCameraUpVectorAndView(HeadComponent head, Coordinate playerPos);
```

2022-10-25 10:25 UTC, jvbsl commented on OctoAwesome/OctoAwesome.Basics/Definitions/Items/WauziItem.cs
> +            simulationRelay?.Dispose();
```suggestion
            simulationRelay.Dispose();
```

2022-10-25 10:25 UTC, jvbsl commented on OctoAwesome/OctoAwesome.Basics/Entities/WauziEntity.cs
> +        /// Gets or sets the time left for jumping.
```suggestion
        /// Gets or sets a value indicating the time left to the next jump.
```

2022-10-25 10:25 UTC, jvbsl commented on OctoAwesome/OctoAwesome.Basics/Entities/WauziEntity.cs
> +                Components.Add(relEntity);
Is that change correct?

2022-10-26 15:01 UTC, susch19 commented on OctoAwesome/OctoAwesome.Basics/Entities/WauziEntity.cs
> +                Components.Add(relEntity);
I have no clue, have to check

2023-06-14 15:35 UTC, jvbsl approved these changes

2023-06-14 15:35 UTC, susch19 commented on OctoAwesome/OctoAwesome.Basics/Entities/WauziEntity.cs
> +                Components.Add(relEntity);
Has already been checked in line 140

2023-06-14 15:35 UTC, merged